name = "lbfgscuda"
uuid = "8d854773-2e1d-4570-8b0f-64c0187236be"
authors = ["Ondřej Matoušek"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[compat]
BenchmarkTools = "1.6.0"
julia = "1.11"
